### ISSUE TITLE
A few comments about the new UI

### ISSUE THREAD

**Issue by bnjbvr** [jsilvestre/tasky#36] opened 2015-04-05 22:15 UTC
Nice rework, especially on mobile! A few UI issues I've noticed so far:
- [x] There is an horizontal scrollbar in the left menu section (Firefox Desktop), while there doesn't appear to be a reason there should be one.
- [x] Hovering over the sort arrow icons shows a pretty big block, way bigger than the icon itself (Firefox Desktop).
- [x] The sort arrows and the "Archived" list name overlap (Firefox OS).
- [ ] Switching the "done" status of a task on mobile (Firefox OS) only shows the orange tick. That is, if you have a task and switch it from "done" to "undone" to "done", then the checkbox is always ticked, with the orange tick.

**Comment by jsilvestre** [comment] 2015-04-05 22:33
Thank you for the report, I didn't polish yet so those kinds of remarks are really valuable. I intend on releasing a polished version with one or two new features.

I'll update you as I go.

**Comment by frankrousseau** [comment] 2015-04-06 13:11
I found a big bug. I have tasks tagged with "#cozy #general" and with "#general #cozy". If I display the list that matches these two tags, it only displays tasks tagged with "#general #cozy".

**Comment by jsilvestre** [comment] 2015-04-06 13:26
It happens this bug has been here for weeks :x Thank you for reporting, I managed to reproduce and I will fix it.

**Comment by frankrousseau** [comment] 2015-04-06 14:09
I updated just today, that's why I noticed it now.

**Comment by jsilvestre** [comment] 2015-04-06 14:18
I didn't notice before actually so that's really "cool" you noticed it so fast! I'm  currently investigating.

**Comment by jsilvestre** [comment] 2015-04-06 14:42
I pushed a new build that should fix your issue @frankrousseau.

**Comment by frankrousseau** [comment] 2015-04-06 14:49
That works! Thank you.

**Comment by jsilvestre** [comment] 2015-11-21 21:42
The last bullet point is about something I won't fix since it's related to the browser itself, and my guess is that it's the browser that messes up.

**Closed by jsilvestre** 2015-11-21 21:42 UTC
Labels: bug
